### ISSUE TITLE
scope being required?  option for when one tree is used for an entire table?

### ISSUE THREAD

**Issue by srevenant** [secretworry/as_nested_set#3]
I may be misreading the documentation, but I don't understand why scope is required.  I can see the use case for having it as an option, but in our case we have a table where the entire table is a single nested set, so I don't need a taxonomy id, I would think.

Thanks!

**Comment by secretworry** [comment]
@srevenant Hi, my mistake to enforce the scope( I originally created the lib to support forests). I'll fix it today.

**Comment by secretworry** [comment]
@srevenant The scope is not required, you can just ignore the `scope` option( which will default to an empty array) and no scope query will be added to your queries :).
Do you find any error when using an empty scope? Considering empty array is just an ordinary case for Array, I didn't write any specified test for it. If any I'd like to fix them:)

**Comment by secretworry** [comment]
I'll fix the misleading `required` in the doc.

**Comment by srevenant** [comment]
Thanks!  I have it writing out a root object, still working on other items.  I'll open another issue with the next question, however :)  Thanks!
