### ISSUE TITLE
parent_id not updating on move

### ISSUE THREAD

**Issue by srevenant** [secretworry/as_nested_set#6]
Earlier I submitted a problem with parent_id not mapping, I think the heart of the problem I'm having is move doesn't appear to be working as I would expect (I would assume it behaves similar to create, in how `target` is the parent for the node, but it seems to be taking the parent_id of the target itself).

I'm probably just not understanding or I'm using it incorrectly, but I'd appreciate some insights.  A simplified example of what I'm doing is receiving a stream of tree changes, that come in with a node_id and parent_id.  The module/struct for the example is `%Tree`.

My code queries the DB to find if the node_id already exists, and if it does it calls `:create` or `:move` appropriately.

In my tests, I do the following sequence of changes:

    1.  %{parent_id: nil, node_id: 100, position: :left}
    2.  %{parent_id: 100, node_id: 101, position: :left}
    3.  %{parent_id: 100, node_id: 102, position: :right}
    4.  %{parent_id: 102, node_id: 103, position: :left}
    5.  %{parent_id: 102, node_id: 104, position: :right}
    6.  %{parent_id: 101, node_id: 103, position: :left}
    7.  %{parent_id: 101, node_id: 103, position: :left}

The problem I'm running into starts at #6, where I submit the request to move node 103 to 101 (pre-existing state at this point is it has a parent of 102).  The result that comes back from .execute() does not have the parent ID changed.  Test #7 should then be returning "duplicate" as the change can be skipped--but it too is failing because it isn't a duplicate, and it tries to do the move again, also failing.

The more involved output:

Request Struct:

    node = %Tree{__meta__: #Ecto.Schema.Metadata<:built, "tree">, id: nil, level: 1, lft: nil, position: 0, rgt: nil, node_id: 103, parent_id: 101}

Current Database Result (before change):

    lookup = %Tree{__meta__: #Ecto.Schema.Metadata<:loaded, "tree">, id: 437, level: 1, lft: 4, position: 0, rgt: 5, node_id: 103, parent_id: 102}

Lookup Desired parent in DB:

    parent = %Tree{__meta__: #Ecto.Schema.Metadata<:loaded, "tree">, id: 435, level: 1, lft: 0, position: 0, rgt: 1, node_id: 101, parent_id: 100}

Commit:

    node
    |> AsNestedSet.move(parent, :left)
    |> AsNestedSet.execute(Repo)
    |> IO.inspect

Result:

    %Tree{__meta__: #Ecto.Schema.Metadata<:loaded, "tree">, id: 437, level: 1, lft: 0, position: 0, rgt: 1, node_id: 103, parent_id: 100}

What is really throwing me off here is that the parent_id is `100`.  This might be a mis-understanding of the docs, but from the shown examples I'd assume that `target` is the parent node.  This is how it seems to work when I do this with `create`, but with `move` it seems to be taking the `parent.parent_id`, instead of `parent.node_id`

Any suggestion/help/insight you can provide is greatly appreciated.

Thanks!

**Comment by secretworry** [comment]
@srevenant Sorry for the delay of answering.

The expression `node |> AsNestedSet.move(parent, :left)` makes the `node` get moved to the left of `parent` ( i.e. as a sibling of `parent`), so the `node` shares the same `parent_id` with `parent`

If you want to move a node to be a child of a specified `parent`, you should use `:child` instead of `:left` as the 3rd-arg. By default this operation makes the `node` as the right-most child of the specified `parent`.
If you want to move the `node` to be the n-th child of a `parent`, you should get the n-th or (n-1)th child of the `parent` and use `move(n_child, :left)` or `move(n_1_child, :right)` respectively.

**Comment by srevenant** [comment]
If I read this right, then `move()` is taking a sibling as the argument, rather than a parent, and you are specifying left/right in respect to the sibling?

You mentioned move with `:child` by default chooses right-most, is there a way to choose left/right-most?  Our trees are only binary (at most 2 children).

**Comment by srevenant** [comment]
working from this assertion, I think I have it working properly now.  I realize looking back on the examples this is probably what is suggested by 'target' ... for posterity, it'd help to explain what target is, and how it changes based on the context of what left/right or child might be.  Thanks!

**Comment by secretworry** [comment]
@srevenant Thanks for the suggestion, I will add more explanation in the README :)
