### ISSUE TITLE
`app: false` creates problem for distillery

### ISSUE THREAD

**Issue by srevenant** [secretworry/as_nested_set#7]
I don't know that this is required in the deps anymore; and it makes it so the app is not available when running as a release.  I have removed it, and it works fine.

**Comment by secretworry** [comment]
It's my mistake to keep the `app: false`, in the version 1.0.0, all the code are generated into the module `use`d the `AsNestedSet`, so as a non-OTP lib, the `as_nested_set` doesn't have to appear in the final project.
